my:
  servers:
    - devexamplecom2
    - anotherexamplecom3


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_example?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
